DecisonTool/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include("Guest.urls")),
    path('Org/',include("Organizer.urls")),
]

Guest/urls.py
from django.urls import path
from Guest import views
app_name="Guest"
urlpatterns = [
    path('org/',views.neworg,name="neworg"),
    path('',views.home,name="home"),
    path('login/',views.login,name="login"),
    path('participate/',views.participate,name="participate"),
    path('interest/',views.interest,name="interest"),
    path('change/interest/',views.change_interest,name="change_interest"),
    path('groups/',views.groups,name="groups"),
]

Organizer/urls.py
from django.urls import path
from Organizer  import views
app_name="org"
urlpatterns = [
    path('home/', views.home,name="home"),
    path('event/', views.events,name="event"),
    path('group/', views.group,name="group"),
    path('capacity/', views.capacity,name="capacity"),
    path('eventview/<int:eid>', views.eventview,name="eventview"),
    path('editevent/<int:eid>', views.editevent,name="editevent"),
    path('finishevent/<int:eid>', views.finishevent,name="finishevent"),
    path('reopenevent/<int:eid>', views.reopenevent,name="reopen"),
    path('deleteevent/<int:eid>', views.deleteevent,name="deleteevent"),
    path('check_and_reassign_rooms/<int:event_id>/', views.check_and_reassign_rooms,name="check_and_reassign_rooms"),
    path('algo/', views.algo,name="algo"),
    path('result/<int:pk>/', views.result,name="result"),
    path('logout/', views.logout,name="logout"),
    path('status/<int:cid>', views.eventstatus,name="status"),
    path('mannual/<int:pk>', views.manuualy,name="manuualy"),
    path('viewcode/<int:pk>', views.view_code,name="view_code"),
    path('ajax/manual/', views.ajax_manual,name="ajax_manual"),
    path('change_capacity/<int:event_id>/', views.change_capacity, name='change_capacity'),
    path('add_capacity/<int:pk>/', views.add_capacity, name='add_capacity'),
]

Guest/models.py
from django.db import models
from Organizer.models import *
# Create your models here.
class organiser(models.Model):
    username=models.CharField(max_length=50,unique=True)
    password=models.CharField(max_length=50,unique=True)
    name=models.CharField(max_length=50)
    email=models.CharField(max_length=50,unique=True)

class ParticipateUser(models.Model):
    user=models.CharField(max_length=50)
    events=models.ForeignKey(Event,on_delete=models.CASCADE)
    rooms=models.TextField(max_length=50,default="")
    new_rooms = models.TextField(max_length=50, default="")
    privatecode = models.TextField(max_length=50, default="")
    is_ignored = models.BooleanField(default=False)

Organizer/models.py
from django.db import models

# Create your models here.
class Event(models.Model):
    code=models.CharField(max_length=50,unique=True)
    rooms=models.IntegerField()
    org=models.ForeignKey("Guest.organiser",on_delete=models.CASCADE)
    status=models.IntegerField(default=0)
    tot_capacity=models.IntegerField(null=True)
    is_private = models.BooleanField(default=False)


class Room(models.Model):
    events=models.ForeignKey(Event,on_delete=models.CASCADE)
    number=models.CharField(max_length=50)
    capacity=models.IntegerField(default=0)



class PrivateCodes(models.Model):
    event=models.ForeignKey(Event,on_delete=models.CASCADE)
    code=models.CharField(max_length=50,unique=True)
    status=models.BooleanField(default=False)

Guest/views.py
from django.shortcuts import render,redirect
from .models import *
from Organizer.models import *
from django.contrib import messages

# Create your views here.
def neworg(request):
    if request.method=="POST":
        organiser.objects.create(username=request.POST.get('txtuname'),password=request.POST.get('txtpass'),name=request.POST.get('txtname'),email=request.POST.get('txtemail'))
        return redirect("Guest:login")
    else:
        return render(request,"Guest/Organizer.html")

def home(request):
    return render(request,"Guest/Home.html")

def login(request):
    error="Invalid UserName and Password"
    if request.method=="POST":
        ocount=organiser.objects.filter(username=request.POST.get('email'),password=request.POST.get('pass')).count()
        if ocount>0:
            odata=organiser.objects.get(username=request.POST.get('email'),password=request.POST.get('pass'))
            request.session["oid"]=odata.id 
            return redirect("org:home")
        else:
            return render(request,"Guest/Login.html",{'mess':error})    
    else:
        return render(request,"Guest/Login.html",)    

def participate(request):
    if request.method=="POST":
        try:
            evntdatacount=Event.objects.filter(code=request.POST.get('txtcode'),status=1).count()
            if evntdatacount>0:
                return render(request,"Guest/Event.html",{'mess':1})
            else:
                is_private=request.POST.get('txt_private')
                
                if is_private == 'public':
                    edata=Event.objects.get(code=request.POST.get('txtcode'),status=0)
                    ParticipateUser.objects.create(user=request.POST.get('txtn'),events=edata)
                    ldata=ParticipateUser.objects.filter(user=request.POST.get('txtn')).last()
                    ids=edata.id
                    idm=ldata.id
                    request.session["edata"]=ids
                    request.session["ldata"]=idm
                    return redirect("Guest:interest")
                else:
                    event_code = request.POST.get('txtcode')
                    username = request.POST.get('txtn')
                    private_code = request.POST.get('txttotal')
                    is_private = request.POST.get('txt_private')

                    event = Event.objects.get(code=event_code, status=0,is_private=True)  # Get the event

                    # Check if the event is private
                    if event:
                        # Check if the private code exists for the event
                        private_code_obj = PrivateCodes.objects.filter(event=event, code=private_code).first()
                        if private_code_obj:

                            
                            # Check if a user with the same private code and username already exists
                            user_exists = ParticipateUser.objects.filter(privatecode=private_code, user=username).exists()
                            if user_exists:
                                messages.warning(request, 'You have already registered for this event with the same private code.')
                                userObj=ParticipateUser.objects.get(user=username, events=event, privatecode=private_code)
                                eId=event.id
                                uId=userObj.id
                                request.session["event_id"]=eId
                                request.session["user_id"]=uId
                                return redirect("Guest:change_interest")
                            else:
                                st=private_code_obj.status
                                if st:
                                    messages.warning(request, 'The private code is already used.')
                                    return render(request,"Guest/Event.html",)
                                # Create a new participant
                                else:
                                    ParticipateUser.objects.create(user=username, events=event, privatecode=private_code)
                                    private_code_obj.status=True
                                    private_code_obj.save()
                                    ldata=ParticipateUser.objects.filter(user=username, events=event, privatecode=private_code).last()
                                    ids=event.id
                                    idm=ldata.id
                                    request.session["edata"]=ids
                                    request.session["ldata"]=idm
                                    messages.success(request, 'Registration successful.')
                                    return redirect("Guest:interest")
                        else:
                            messages.error(request, 'Invalid private code for this event.')
                    else:
                        # Event is not private, create a new participant
                        messages.error(request, 'the event is not a private event.')

                    return redirect("Guest:interest")
            
        except Exception as e:
            print(e)
            messages.error(request,"Event code is not Valid please try with a new one")
            return render(request,"Guest/Event.html",)
    else:
        return render(request,"Guest/Event.html")

def interest(request):
    edata=Event.objects.get(id=request.session["edata"])
    gdata=Room.objects.filter(events=edata)
   
    if request.method=="POST":
        pdata=ParticipateUser.objects.get(id=request.session["ldata"])
        pdata.rooms=request.POST.getlist('inte')
        pdata.save()
        return redirect("Guest:participate")
    else:
        return render(request,"Guest/Group.html",{'data':gdata})
    
def change_interest(request):
    edata=Event.objects.get(id=request.session["event_id"])
    gdata=Room.objects.filter(events=edata)
    user_record = ParticipateUser.objects.get(id=request.session["user_id"])
    user_preferences = user_record.rooms 

    context = {
    'data': gdata,
    'user_preferences': user_preferences
}
    if request.method=="POST":
        pdata=ParticipateUser.objects.get(id=request.session["user_id"])
        pdata.rooms=request.POST.getlist('inte')
        pdata.save()
        return redirect("Guest:participate")
    else:
        return render(request,"Guest/change_preference.html",context)

def groups(request):
    ldata=ParticipateUser.objects.get(id=request.session["ldata"])
    #print(ldata)
    if request.GET.get('did')=="yes":
        roomdata=ldata.rooms
        if roomdata=="":
            roomdata=roomdata+str(request.GET.get('cid'))
            ldata.rooms=roomdata
            ldata.save()
            return redirect("Guest:interest")
        else:
            roomdata=roomdata+","+str(request.GET.get('cid'))
            ldata.rooms=roomdata
            ldata.save()
            return redirect("Guest:interest")
        # gp=room.objects.get(id=request.GET.get('cid'))
        # counts=int(gp.capacity)
        # dcount=ParticipateUser.objects.filter(rooms=gp).count()
        # if dcount>counts:
        #     return redirect("Guest:home")
        # else:
        #     ldata.rooms=gp
        #     ldata.save()
        #     return redirect("Guest:interest")
    else:
        return redirect("Guest:interest")

Guest/templates/Guest/Event.html
{% extends 'Guest/Head.html'%}
{% load static %}
{% block content %}
<br><br><br><br>
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>

<body>
    <div id="tab">
        <form action="" method="post">
            {% csrf_token %}
            <table border="1" align="center" cellpadding="10">
                <tr>
                    <td>EVENT CODE</td>
                    <td><input type="text" name="txtcode" id="" required></td>
                </tr>
                <tr>
                    <td>Participant Name</td>
                    <td><input type="text" name="txtn" id="" required></td>
                </tr>
                <tr>
                    <td>Type of Event</td>
                    <td>
                        <input type="radio" name="txt_private" id="public" value="public" required="required">Public
                        <input type="radio" name="txt_private" id="private" value="private" required="required">Private
                    </td>
                </tr>

                <tr id="totalCapacityRow" style="display: none;">
                    <td>Enter Your Code</td>
                    <td><input type="txt" name="txttotal" id="txttotal"></td>
                </tr>
                <tr>
                    <td colspan="2" align="right"><input type="submit" value="Next" name="btn"></td>
                </tr>
            </table>
            <!-- {% if messages %}
        {% for message in messages %}
        <div class="alert  {% if message.tags == 'success' %} alert-success {% elif message.tags == 'error' %} alert-danger  {% endif %} alert-dismissible fade show"
            data-timeout="3000" role="alert">
            {{message}}
            <button type="button" class="btn btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
        </div>
        {% endfor %}
        {% endif %} -->
            {% if mess == 1 %}
            <script>
                alert("This Event is Already Finished Try Any Other Events");
                window.location = "";
            </script>

            {% endif %}
            <!--  -->
            {% if messages %}
            {% for message in messages %}
            <div class="alert  {% if message.tags == 'success' %} alert-success {% elif message.tags == 'error' %} alert-danger {% elif message.tags == 'warning' %} alert-warning {% endif %} alert-dismissible fade show"
                data-timeout="3000" role="alert">
                {{message}}
                <button type="button" class="btn btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
            </div>
            {% endfor %}
            {% endif %}
        </form>
    </div>
    <script>
        document.addEventListener('DOMContentLoaded', function () {
            const privateRadio = document.getElementById('private');
            const totalCapacityRow = document.getElementById('totalCapacityRow');

            privateRadio.addEventListener('change', function () {
                if (this.checked) {
                    totalCapacityRow.style.display = 'table-row';
                } else {
                    totalCapacityRow.style.display = 'none';
                }
            });

            const publicRadio = document.getElementById('public');

            publicRadio.addEventListener('change', function () {
                if (this.checked) {
                    totalCapacityRow.style.display = 'none';
                }
            });
        });
    </script>
</body>

</html>
<br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br>
{% endblock content %}

Guest/templates/Guest/Group.html
{% extends 'Guest/Head.html'%}
{% load static %}
{%  block content %}
<br><br><br><br>
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <form action="" method="post" id="groupform"  data-group-url="{% url 'Guest:groups'%}">
        {% csrf_token %}
        <table align="center" cellpading="10">
            {% for i in data %}
            <tr>
                <td>{{i.number}} Interested</td>
                <td>
                    <input type="checkbox" name="inte" id="" value="{{i.number}}"  class="selc">Yes
                </td>
            </tr>
            {% endfor %}
            <tr>
                <td colspan="2" align="right"><input type="submit" value="Submit" name="btn"></td>
            </tr>
        </table>
        {% if mess %}
        <script>
            alert("You have Provieded your Interest Wait For Results Updates");
            window.location="";
        </script>
        {% endif %}
    </form>
</body>
</html>
<!-- <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
<script>
    $(".selc").change(function () {
        var did = $(this).val();
        var cid=$(this).attr('alt');
        //alert(did); 
        var ur = $("#groupform").attr("data-group-url");
        $.ajax({
            url: ur,
            data: { did: did,cid:cid },
            success: function (data) {
               
            },
        });
       
    }); -->
</script>
<br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br>
{% endblock content %}

Guest/templates/Guest/Head.html
{% load static %}
<!DOCTYPE html>
<html lang="zxx">

<head>
    <meta charset="UTF-8">
    <meta name="description" content="Manup Template">
    <meta name="keywords" content="Manup, unica, creative, html">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Groupy</title>

    <!-- Google Font -->
    <link href="https://fonts.googleapis.com/css?family=Work+Sans:400,500,600,700,800,900&display=swap"
        rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Poppins:400,500,600,700&display=swap" rel="stylesheet">


    <!-- Css Styles -->
    <link rel="stylesheet" href="{% static 'Main/css/bootstrap.min.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'Main/css/font-awesome.min.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'Main/css/elegant-icons.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'Main/css/owl.carousel.min.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'Main/css/magnific-popup.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'Main/css/slicknav.min.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'Main/css/style.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'Form/form.css' %}" />
</head>

<body>
    <!-- Page Preloder -->
    <div id="preloder">
        <div class="loader"></div>
    </div>

    <!-- Header Section Begin -->
    <header class="header-section">
        <div class="container">
            <div class="logo" style="padding-top: 15px !important;">
                <a href="{% url 'Guest:home'%}">
                    <img src="{% static 'img.png' %}" alt="" width="150" height="150">
                </a>
            </div>
            <div class="nav-menu" style="padding-top: 36px;">
                <nav class="mainmenu mobile-menu">
                    <ul>
                        <li class="active"><a href="{% url 'Guest:home'%}">Home</a></li>
                        <li><a href="{% url 'Guest:login' %}">Orgaziner</a></li>
                        <!-- <li><a href="./speaker.html">Participe</a>
                            <ul class="dropdown">
                                <li><a href="#">Jayden</a></li>
                                <li><a href="#">Sara</a></li>
                                <li><a href="#">Emma</a></li>
                                <li><a href="#">Harriet</a></li>
                            </ul>
                        </li>
                        <li><a href="./schedule.html">Schedule</a></li>
                        <li><a href="./blog.html">Blog</a></li>
                        <li><a href="./contact.html">Contacts</a></li> -->
                    </ul>
                </nav>
                <a href="{% url 'Guest:participate' %}" class="primary-btn top-btn"><i class="fa fa-ticket"></i> Participate</a>
            </div>
            <div id="mobile-menu-wrap"></div>
        </div>
    </header>
    <!-- Header End -->

    {% block content %}

    {% endblock content %}

    <script>
        // Automatically close the notification after 5 seconds
        setTimeout(function() {
          var notification = document.querySelector('.alert');
          notification.style.display = 'none';
        }, 3000);
      </script>
    
    <!-- Js Plugins -->
    <script src="{% static 'Main/js/jquery-3.3.1.min.js' %}"></script>
    <script src="{% static 'Main/js/bootstrap.min.js' %}"></script>
    <script src="{% static 'Main/js/jquery.magnific-popup.min.js' %}"></script>
    <script src="{% static 'Main/js/jquery.countdown.min.js' %}"></script>
    <script src="{% static 'Main/js/jquery.slicknav.js' %}"></script>
    <script src="{% static 'Main/js/owl.carousel.min.js' %}"></script>
    <script src="{% static 'Main/js/main.js' %}"></script>

Guest/templates/Guest/Login.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
	<title>Login V1</title>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
<!--===============================================================================================-->	
	<link rel="icon" type="image/png" href="{% static 'Login/images/icons/favicon.ico' %}"/>
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static 'Login/vendor/bootstrap/css/bootstrap.min.css' %}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static 'Login/fonts/font-awesome-4.7.0/css/font-awesome.min.css' %}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static 'Login/vendor/animate/animate.css' %}">
<!--===============================================================================================-->	
	<link rel="stylesheet" type="text/css" href="{% static 'Login/vendor/css-hamburgers/hamburgers.min.css' %}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static 'Login/vendor/select2/select2.min.css' %}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static 'Login/css/util.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'Login/css/main.css' %}">
<!--===============================================================================================-->
</head>
<body>
	
	<div class="limiter">
		<div class="container-login100">
			<div class="wrap-login100">
				<div class="login100-pic js-tilt" data-tilt>
					<img src="{% static 'Login/images/img-01.png' %}" alt="IMG">
				</div>

				<form class="login100-form" method="post">
                    {% csrf_token %}
					<span class="login100-form-title">
						Member Login
					</span>

					<div class="wrap-input100" >
						<input class="input100" type="text" name="email" placeholder="Email">
						<span class="focus-input100"></span>
						<span class="symbol-input100">
							<i class="fa fa-envelope" aria-hidden="true"></i>
						</span>
					</div>

					<div class="wrap-input100 ">
						<input class="input100" type="password" name="pass" placeholder="Password">
						<span class="focus-input100"></span>
						<span class="symbol-input100">
							<i class="fa fa-lock" aria-hidden="true"></i>
						</span>
					</div>
					
					<div class="container-login100-form-btn">
						<button class="login100-form-btn" type="submit" name="btn">
							Login
						</button>
					</div>

					<div class="text-center p-t-12">
						<span class="txt1">
							Forgot
						</span>
						<a class="txt2" href="#">
							Username / Password?
						</a>
					</div>

					<div class="text-center p-t-136">
						<a class="txt2" href="{% url 'Guest:neworg' %}">
							Create your Account
							<i class="fa fa-long-arrow-right m-l-5" aria-hidden="true"></i>
						</a>
					</div>
				</form>
				{% if mess %}
				{{mess}} 
				
				{% endif %}
			</div>
		</div>
	</div>
	
	

	
<!--===============================================================================================-->	
	<script src="{% static 'Login/vendor/jquery/jquery-3.2.1.min.js' %}"></script>
<!--===============================================================================================-->
	<script src="{% static 'Login/vendor/bootstrap/js/popper.js' %}"></script>
	<script src="{% static 'Login/vendor/bootstrap/js/bootstrap.min.js' %}"></script>
<!--===============================================================================================-->
	<script src="{% static 'Login/vendor/select2/select2.min.js' %}"></script>
<!--===============================================================================================-->
	<script src="{% static 'Login/vendor/tilt/tilt.jquery.min.js' %}"></script>
	<script >
		$('.js-tilt').tilt({
			scale: 1.1
		})
	</script>
<!--===============================================================================================-->
	<script src="{% static 'Login/js/main.js' %}"></script>

</body>
</html>

Guest/templates/Guest/Organizer.html
{% extends 'Guest/Head.html'%}
{% load static %}
{%  block content %}
<br><br><br><br>
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>New</title>
</head>
<body>
    <div id="tab">
    <form action="" method="post">
        {% csrf_token %}
        <table border="1" align="center" cellpadding="10">
            <tr>
                <td>USER NAME</td>
                <td><input type="text" name="txtuname" id="" required="" autocomplete="off"></td>
            </tr>
            <tr>
                <td>Password</td>
                <td><input type="password" name="txtpass" id="" required="" autocomplete="off"></td>
            </tr>
            <tr>
                <td>Name</td>
                <td><input type="text" name="txtname" id="" required="" autocomplete="off"></td>
            </tr>
            <tr>
                <td>Email</td>
                <td><input type="email" name="txtemail" id="" required="" autocomplete="off"></td>
            </tr>
            <tr>
                <td colspan="2" align="right"><input type="submit" value="Register" name="btn"></td>
            </tr>

        </table>
    </form>
</div>
{% if messages %}
{% for message in messages %}
<div class="alert  {% if message.tags == 'success' %} alert-success {% elif message.tags == 'error' %} alert-danger  {% endif %} alert-dismissible fade show"
    data-timeout="3000" role="alert">
    {{message}}
    <button type="button" class="btn btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
</div>
{% endfor %}
{% endif %}
</body>
</html>
<br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br>
{% endblock content %}

Guest/templates/Guest/change_preference.html
{% extends 'Guest/Head.html'%}
{% load static %}
{%  block content %}
<br><br><br><br>
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h4 class="text-center">Change Preference</h4>
    <form action="" method="post" id="groupform"  data-group-url="{% url 'Guest:groups'%}">
        {% csrf_token %}
        <table align="center" cellpading="10">
            {% for i in data %}
            <tr>
                <td>{{i.number}} Interested</td>
                <td>
                    <input type="checkbox" name="inte" id="" value="{{i.number}}" class="selc"
                           {% if i.number in user_preferences %}checked{% endif %}>Yes
                </td>
            </tr>
            {% endfor %}
            <tr>
                <td colspan="2" align="right"><input type="submit" value="Submit" name="btn"></td>
            </tr>
        </table>
        {% if mess %}
        <script>
            alert("You have Changed your Interest Wait For Results Updates");
            window.location="";
        </script>
        {% endif %}
    </form>
</body>
</html>
<!-- <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
<script>
    $(".selc").change(function () {
        var did = $(this).val();
        var cid=$(this).attr('alt');
        //alert(did); 
        var ur = $("#groupform").attr("data-group-url");
        $.ajax({
            url: ur,
            data: { did: did,cid:cid },
            success: function (data) {
               
            },
        });
       
    }); -->
</script>
<br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br>
{% endblock content %}