DecisonTool/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include("Guest.urls")),
    path('Org/',include("Organizer.urls")),
]

Guest/urls.py
from django.urls import path
from Guest import views
app_name="Guest"
urlpatterns = [
    path('org/',views.neworg,name="neworg"),
    path('',views.home,name="home"),
    path('login/',views.login,name="login"),
    path('participate/',views.participate,name="participate"),
    path('interest/',views.interest,name="interest"),
    path('change/interest/',views.change_interest,name="change_interest"),
    path('groups/',views.groups,name="groups"),
]

Organizer/urls.py
from django.urls import path
from Organizer  import views
app_name="org"
urlpatterns = [
    path('home/', views.home,name="home"),
    path('event/', views.events,name="event"),
    path('group/', views.group,name="group"),
    path('capacity/', views.capacity,name="capacity"),
    path('eventview/<int:eid>', views.eventview,name="eventview"),
    path('editevent/<int:eid>', views.editevent,name="editevent"),
    path('finishevent/<int:eid>', views.finishevent,name="finishevent"),
    path('reopenevent/<int:eid>', views.reopenevent,name="reopen"),
    path('deleteevent/<int:eid>', views.deleteevent,name="deleteevent"),
    path('check_and_reassign_rooms/<int:event_id>/', views.check_and_reassign_rooms,name="check_and_reassign_rooms"),
    path('algo/', views.algo,name="algo"),
    path('result/<int:pk>/', views.result,name="result"),
    path('logout/', views.logout,name="logout"),
    path('status/<int:cid>', views.eventstatus,name="status"),
    path('mannual/<int:pk>', views.manuualy,name="manuualy"),
    path('viewcode/<int:pk>', views.view_code,name="view_code"),
    path('ajax/manual/', views.ajax_manual,name="ajax_manual"),
    path('change_capacity/<int:event_id>/', views.change_capacity, name='change_capacity'),
    path('add_capacity/<int:pk>/', views.add_capacity, name='add_capacity'),
]

Organizer/models.py
from django.db import models

# Create your models here.
class Event(models.Model):
    code=models.CharField(max_length=50,unique=True)
    rooms=models.IntegerField()
    org=models.ForeignKey("Guest.organiser",on_delete=models.CASCADE)
    status=models.IntegerField(default=0)
    tot_capacity=models.IntegerField(null=True)
    is_private = models.BooleanField(default=False)


class Room(models.Model):
    events=models.ForeignKey(Event,on_delete=models.CASCADE)
    number=models.CharField(max_length=50)
    capacity=models.IntegerField(default=0)



class PrivateCodes(models.Model):
    event=models.ForeignKey(Event,on_delete=models.CASCADE)
    code=models.CharField(max_length=50,unique=True)
    status=models.BooleanField(default=False)

Organizer/views.py
import math
import random
import string
from django.shortcuts import render,redirect,HttpResponse
from django.urls import reverse
from urllib.parse import urlencode
from Guest.models import *
from Organizer.models import Room,Event
import networkx as nx
from Organizer.templatetags import custom_filters
from django.shortcuts import get_object_or_404
import numpy as np
from scipy.optimize import linear_sum_assignment
from django.contrib import messages
from ast import literal_eval
from django.http import HttpResponse, HttpResponseRedirect, JsonResponse
OTPdigits = "123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ"
# Create your views here.
def home(request):
    if 'oid' in request.session:
        orgdata=organiser.objects.get(id=request.session["oid"])
        evendata=Event.objects.filter(org=orgdata)
        return render(request,"Organizer/Home.html",{'data':evendata})
    else:
        return redirect("Guest:login")
    
def generate_code():
    characters = string.ascii_letters + string.digits
    code = ''.join(random.choice(characters) for _ in range(6))
    return code

def events(request):
    if 'oid' in request.session:
        if request.method=="POST":
            data=organiser.objects.get(id=request.session["oid"])
            try:
                is_private=request.POST.get('txt_private')
                
                if is_private == 'public':
                    Event.objects.create(code=request.POST.get('txtcode'),rooms=request.POST.get('txtn'),org=data)
                    counts=int(request.POST.get('txtn'))
                    eventid=Event.objects.filter(org=data).last()
                    ids=eventid.id
                    for i in range(1,counts+1):
                        names="Group"+str(i)
                        #print(names)
                        Room.objects.create(number=names,events=eventid)
                    request.session["events"]=ids
                    return redirect("org:group")
                else:
                    totl_Cap=int(request.POST.get('txttotal'))
                    Event.objects.create(code=request.POST.get('txtcode'),rooms=request.POST.get('txtn'),org=data,is_private=True,tot_capacity=totl_Cap)
                    counts=int(request.POST.get('txtn'))
                    eventid=Event.objects.filter(org=data).last()
                    ids=eventid.id
                    for i in range(1,counts+1):
                        names="Group"+str(i)
                        #print(names)
                        Room.objects.create(number=names,events=eventid)
                    code = ""
                    for j in range(totl_Cap):
                        code = generate_code()
                        PrivateCodes.objects.create(event=eventid, code=code)
                    request.session["events"]=ids
                    return redirect("org:group")
            except Exception as e:
                    # print(e)
                messages.error(request, 'Event ID is Repeating Please Try again!')
                return render(request,"Organizer/Event.html")
            
        else:
            return render(request,"Organizer/Event.html")
    else:
        return redirect("Guest:login")

def group(request):
    eventadta=Event.objects.get(id=request.session["events"])
    roomdata=Room.objects.filter(events=eventadta)
    if request.method=="POST":
        return render(request,"Organizer/Group.html",{'mess':1})
    else:
        return render(request,"Organizer/Group.html",{'room':roomdata,'event':eventadta})

def capacity(request):
    data=request.GET.get('did')
    cap,gp=data.split(",")
    roomdata=Room.objects.get(id=gp)
    roomdata.capacity=cap
    roomdata.save()
    return redirect("org:group")

def change_capacity(request, event_id):
    event = Event.objects.get(id=event_id)
    rooms = Room.objects.filter(events=event)
    
    if request.method == "POST":
        for key, value in request.POST.items():
            if key.startswith("room_") and key.endswith("_capacity"):
                room_number = key.split("_")[1]
                room = Room.objects.get(events=event, number=room_number)
                room.capacity = value
                room.save()
        return redirect('org:home')  # Redirect to a success page
    else:
        return render(request, 'Organizer/group_edit.html', {'event': event, 'rooms': rooms})

def eventview(request,eid):
    data=Event.objects.get(id=eid)
    return render(request,"Organizer/eventview.html",{'data':data})

def editevent(request,eid):
    data=Event.objects.get(id=eid)
    if request.method=="POST":
        data.code=request.POST.get('txtcode')
        data.save()
        return redirect("org:home")
    else:
        return render(request,"Organizer/editevent.html",{'data':data})

def finishevent(request,eid):
    data=Event.objects.get(id=eid)
    data.status=1
    data.save()
    request.session["eid"]=eid
    # params = urlencode({'event_id': eid})
    # url = reverse('org:check_and_reassign_rooms') + f'?{params}'
    # return redirect(url)
    return redirect(reverse('org:check_and_reassign_rooms', kwargs={'event_id': eid}))

def deleteevent(request,eid):
    data=Event.objects.get(id=eid)
    data.delete()
    return redirect('org:home')

def reopenevent(request,eid):
    data=Event.objects.get(id=eid)
    data.status=0
    data.save()
    return redirect('org:home')


def logout(request):
    del request.session["oid"]
    return redirect("Guest:home")

def allocate_groups(request,did):
    participents={}
    groups = {}
    mylist=[]
    eventdata=Event.objects.get(id=did)
    eventdata=Event.objects.get(id=did)
    pdatacount=ParticipateUser.objects.filter(events=eventdata).count()
    if pdatacount>0:
        pdata=ParticipateUser.objects.filter(events=eventdata)
        roomsdata=Room.objects.filter(events=eventdata)
        for i in roomsdata:
            
            groups[i.number]=i.capacity
        
        for  i in pdata:
            for j in roomsdata:
                if j.number in i.rooms:
                    if j.number in mylist:
                        continue
                    else:
                        mylist.append(j.number)
            participents[i.user]=mylist
        print(mylist)
        #print(groups)
        print(participents)
        B = nx.Graph()
        B.add_nodes_from(participents.keys(), bipartite=0)
        B.add_nodes_from(groups.keys(), bipartite=1)


        for participent_name, participent_groups in participents.items():
            for group_name in participent_groups:
                B.add_edge(participent_name, group_name, weight=1)
        
        matching = nx.bipartite.maximum_matching(B, top_nodes=participents.keys())

        allocations = {}
        for participent_name, group_name in matching.items():
            if group_name not in allocations:
                allocations[group_name] = []
            allocations[group_name].append(participent_name)
        
        for group_name, participents in allocations.items():
        
            print(f" - {participent_name}-{group_name}")
            print()
        
        
        return render(request,"Organizer/ViewPart.html",{'data':allocations,'room':roomsdata})
    else:
        return render(request,"Organizer/ViewPart.html")
    


def algo(request):
    participents={}
    groups = {}
    mylist=[]
    eventdata=Event.objects.get(id=request.session["eid"])
    
    pdatacount=ParticipateUser.objects.filter(events=eventdata).count()
    if pdatacount>0:
        pdata=ParticipateUser.objects.filter(events=eventdata)
        roomsdata=Room.objects.filter(events=eventdata)
        for i in roomsdata:
            
            groups[i.number]=i.capacity
        
        for  i in pdata:
            for j in roomsdata:
                if j.number in i.rooms:
                    if j.number in mylist:
                        continue
                    else:
                        mylist.append(j.number)
            participents[i.user]=mylist
        print(mylist)
        #print(groups)
        print(participents)
        B = nx.Graph()
        B.add_nodes_from(participents.keys(), bipartite=0)
        B.add_nodes_from(groups.keys(), bipartite=1)


        for participent_name, participent_groups in participents.items():
            for group_name in participent_groups:
                B.add_edge(participent_name, group_name, weight=1)
        
        matching = nx.bipartite.maximum_matching(B, top_nodes=participents.keys())

        allocations = {}
        for participent_name, group_name in matching.items():
            if group_name not in allocations:
                allocations[group_name] = []
            allocations[group_name].append(participent_name)
        
        for group_name, participents in allocations.items():
        
            print(f" - {participent_name}-{group_name}")
            print()
        
        
        return render(request,"Organizer/ViewPart.html",{'data':allocations,'room':roomsdata})
    else:
        return render(request,"Organizer/ViewPart.html")
    
    # eventdata=event.objects.get(id=did)
    # roomdata=room.objects.filter(events=eventdata)
    
    # print(groups)
    # return render(request,"Organizer/Home.html")
    
def eventstatus(request,cid):
    try:    
        eventdata=Event.objects.get(id=cid)
        pdata=ParticipateUser.objects.filter(events=eventdata)
        roomdata=Room.objects.filter(events=eventdata)
        
        return render(request, "Organizer/Status.html", {'data': pdata, 'rdata': roomdata,})

    except Exception as e:
        messages.error(request, 'No user is registered for this event!')
        return render(request, "Organizer/Status.html",{'rdata':roomdata})



def allocate_rooms(request, event_id):
    event = get_object_or_404(Event, id=event_id)
    participants = ParticipateUser.objects.filter(events=event)
    rooms = Room.objects.filter(events=event)

    # Create a directed graph

Organizer/templates/Organizer/Group.html
{% extends 'Organizer/Head.html'%}
{% load static %}
{%  block content %}
<br><br><br><br>
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body bgcolor="cyan">
    <h3 class="text-center fw-bold">Room Capacity</h3>
    <form action="" method="post" id="groupform" data-group-url="{% url 'org:capacity'%}" onsubmit="return validateCapacity()">
        {% csrf_token %}
        <table align="center" cellpadding="10">
           <input type="hidden" name="txttotal" id="txttotal" value="{{event.tot_capacity}}">
            {% for i in room %}

             <tr>
                <td>Group{{forloop.counter}}</td>
                <td><select name="selc" class="selc" required>
                        <option value="">---Select---</option>
                        <option value="1,{{i.id}}">1</option>
                        <option value="2,{{i.id}}">2</option>
                        <option value="3,{{i.id}}">3</option>
                        <option value="4,{{i.id}}">4</option>
                        <option value="5,{{i.id}}">5</option>
                        <option value="6,{{i.id}}">6</option>
                        <option value="7,{{i.id}}">7</option>
                        <option value="8,{{i.id}}">8</option>
                        <option value="9,{{i.id}}">9</option>
                        <option value="10,{{i.id}}">10</option>
                        <option value="11,{{i.id}}">11</option>
                        <option value="12,{{i.id}}">12</option>
                        <option value="13,{{i.id}}">13</option>
                        <option value="14,{{i.id}}">14</option>
                        <option value="15,{{i.id}}">15</option>
                        <option value="16,{{i.id}}">16</option>
                        <option value="17,{{i.id}}">17</option>
                        <option value="18,{{i.id}}">18</option>
                        <option value="19,{{i.id}}">19</option>
                        <option value="20,{{i.id}}">20</option>
                        <option value="21,{{i.id}}">21</option>
                        <option value="22,{{i.id}}">22</option>
                        <option value="23,{{i.id}}">23</option>
                        <option value="24,{{i.id}}">24</option>
                        <option value="25,{{i.id}}">25</option>
                </select></td>
             </tr>  
             {% endfor %} 
             <tr>
                <td colspan="2" align="right"><input type="submit" value="Next" id="submit" name="btn"></td>
             </tr>
        </table>
        {% if mess %}
        <script>
            alert("YOU HAVE CREATED THE EVENT PLEASE PROVIDE EVENTNAME TO USER FOR SET THEIR PREFERENCE");
            window.location="../../Org/home";
        </script>
        {% endif %}
    </form>
</body>
</html>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
<script>
    $(".selc").change(function () {
        var did = $(this).val();
        //alert(did); 
        var ur = $("#groupform").attr("data-group-url");
        $.ajax({
            url: ur,
            data: { did: did, },
            success: function (data) {
               
            },
        });
    });

    function validateCapacity() {
        var totalCapacity = parseInt(document.getElementById("txttotal").value);
        var selectedOptions = document.querySelectorAll(".selc");
        var selectedCapacity = 0;

        // Calculate the sum of selected capacities
        selectedOptions.forEach(function (option) {
            var capacity = parseInt(option.value.split(",")[0]);
            selectedCapacity += capacity;
        });

        // Check if the selected capacity exceeds the total capacity
        if (totalCapacity !== null && selectedCapacity > totalCapacity) {
            alert("Total capacity exceeded. Please adjust the group capacities.");
            return true; // Allow form submission
        }

        return true; // Allow form submission
    }
</script>


<br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br>
{% endblock content %}

Organizer/templates/Organizer/Head.html
{% load static %}
<!DOCTYPE html>
<html lang="zxx">

<head>
    <meta charset="UTF-8">
    <meta name="description" content="Manup Template">
    <meta name="keywords" content="Manup, unica, creative, html">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Groupy</title>

    <!-- Google Font -->
    <link href="https://fonts.googleapis.com/css?family=Work+Sans:400,500,600,700,800,900&display=swap"
        rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Poppins:400,500,600,700&display=swap" rel="stylesheet">


    <!-- Css Styles -->
    <link rel="stylesheet" href="{% static 'Main/css/bootstrap.min.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'Main/css/font-awesome.min.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'Main/css/elegant-icons.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'Main/css/owl.carousel.min.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'Main/css/magnific-popup.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'Main/css/slicknav.min.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'Main/css/style.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'Form/form.css' %}" />
</head>

<body>
    <!-- Page Preloder -->
    <div id="preloder">
        <div class="loader"></div>
    </div>

    <!-- Header Section Begin -->
    <header class="header-section">
        <div class="container">
            <div class="logo" style="padding-top: 15px !important;">
                <a href="{% url 'Guest:home'%}">
                    <img src="{% static 'img.png' %}" alt="" width="150" height="150">
                </a>
            </div>
            <div class="nav-menu" style="padding-top:36px ;">
                <nav class="mainmenu mobile-menu">
                    <ul>
                        <li class="active"><a href="{% url 'org:home'%}">Home</a></li>
                        <!-- <li><a href="{% url 'Guest:login' %}">Orgaziner</a></li> -->
                        <!-- <li><a href="./speaker.html">Participe</a>
                            <ul class="dropdown">
                                <li><a href="#">Jayden</a></li>
                                <li><a href="#">Sara</a></li>
                                <li><a href="#">Emma</a></li>
                                <li><a href="#">Harriet</a></li>
                            </ul>
                        </li>
                        <li><a href="./schedule.html">Schedule</a></li>
                        <li><a href="./blog.html">Blog</a></li>
                        <li><a href="./contact.html">Contacts</a></li> -->
                    </ul>
                </nav>
                <a href="{% url 'org:logout' %}" class="primary-btn top-btn">Logout</a>
            </div>
            <div id="mobile-menu-wrap"></div>
        </div>
    </header>
    <!-- Header End -->

    {% block content %}
    
    {% endblock content %}

    <script>
        // Automatically close the notification after 5 seconds
        setTimeout(function() {
          var notification = document.querySelector('.alert');
          notification.style.display = 'none';
        }, 3000);
      </script>

    <!-- Js Plugins -->
    <script src="{% static 'Main/js/jquery-3.3.1.min.js' %}"></script>
    <script src="{% static 'Main/js/bootstrap.min.js' %}"></script>
    <script src="{% static 'Main/js/jquery.magnific-popup.min.js' %}"></script>
    <script src="{% static 'Main/js/jquery.countdown.min.js' %}"></script>
    <script src="{% static 'Main/js/jquery.slicknav.js' %}"></script>
    <script src="{% static 'Main/js/owl.carousel.min.js' %}"></script>
    <script src="{% static 'Main/js/main.js' %}"></script>

Organizer/templates/Organizer/Home.html
{% extends 'Organizer/Head.html'%}
{% load static %}
{%  block content %}
<br><br><br><br>

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <form action="" method="post">
        {% csrf_token %}
        <table align="center" cellpadding="10">
            <tr>
                <td colspan="4" align="center">
                    <a href="{% url 'org:event' %}"><img src="{% static 'Img/add.png'%}">
                    <p>Create event</p>
                </a>
                </td>

            </tr>
           <tr>
            {% for i in data %}
              
            <td>
              <a href="{% url 'org:eventview' i.id %}" style="text-decoration: none;">
                <div style="text-align:center;border:1px solid black;margin:22px;padding:20px">

                    <p>{{i.code}}</p>
                  
                </div></a>
            </td>
            {% if forloop.counter|divisibleby:4 %}
        </tr>
        <tr>
            {% endif %}


            {% endfor %}
            
        </table>
    </form>
</body>
</html>
<br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br>
{% endblock content %}

Organizer/templates/Organizer/Manually.html
{% extends 'Organizer/Head.html'%}
{% load static %}


{% block content %}
<br><br><br><br>
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet">
</head>

<body>
<div class="row">
    <div class="col-md-6">
        <form action="" method="post">
            {% csrf_token %}
            <table border="1" align="center" cellpadding="10"  >
    
                {% for user_data in users_data %}
                <tr>
                    <td>
                        <p>{{ user_data.user }}</p>
                    </td>
    
                    <td>
                        <select id="room_{{ user_data.id }}" name="room_{{ user_data.id }}"  onchange="onSelectChange(this.value, '{{ user_data.id }}')">
                            <option value="">Select Room</option>
                            {% for room in room %}
                            <option value="{{ room.id }}" {% if user_data.new_rooms == room.number %}selected {% endif %} >
                                {{ room.number }}
                            </option>
                            {% endfor %}
                        </select>
                    </td>
    
                </tr>
                {% endfor %}
                <!-- <tr>
                    <td colspan="2" align="right"><input type="submit" value="Update" name="btn"></td>
                </tr> -->
            </table>
    
          
        </form>
    </div>
    
       <div class="col-md-6">
        <h4 class="text-center">preferences</h4>
        <table  align="center" cellpadding="10">
            <tr>
                {% for i in rdata %}
                <td>
                    <div style="text-align:center;border:1px solid black;margin:22px;padding:20px">
                    {{i.number}}  - capacity : {{ i.capacity }}
                    {% for j in data %}
                    {% if i.number in j.rooms %}
    
    
                        <p>{{j.user}}</p>
    
    
    
    
                    {% endif %}
                    {% endfor %}
                </div>
                </td>
                {% if forloop.counter|divisibleby:4 %}
            </tr>
            <tr>
                {% endif %}
                {% endfor %}
    
        </table>
       </div>
</div>
    <div id="message-container"></div>
   

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>

<!-- <script>
    $(document).ready(function () {
        // $('.card-link').click(function (e) {
        //     e.preventDefault();
        //     // Perform desired action when the link is clicked
        // });

        $("#room").change(function () {
            var studentId = $(this).val();
            alert(studentId)
            $.ajax({
                url: '/ajax/manual/',
                data: { studentId: studentId, },
                type: 'GET',

                success: function (response) {
                    $('#resume-section').html(response);
                },
                error: function (xhr, status, error) {
                    console.log(error);
                }
            });
        });
    });
</script> -->
<script>
    function onSelectChange(selectedValue, userId) {
        // Use the selectedValue and userId to perform your AJAX call
        // For example, using jQuery AJAX
        $("#message-container").html(""); 
        $.ajax({
            type: "GET",
            url: "{% url 'org:ajax_manual' %}",  // Replace 'your_ajax_view_url' with the URL of your AJAX view
            data: {
                selected_value: selectedValue,
                user_id: userId
            },
            success: function (data) {
            // Handle the response from the server
            if (data.message === "Success") {
                // Room is available, perform actions as needed
                console.log(data);
            } else if (data.message === "Error") {
                // Room is not available, show the error message
                // console.log(data);
                var i =0;
                alert(data.result);
                // {% for message in messages %}
                // Use the same message code in the HTML page
                
                // var alertClass = "alert ";
                // if ("{{ message.tags }}" === "success") {
                //     alertClass += "alert-success";
                // } else if ("{{ message.tags }}" === "error") {
                //     alertClass += "alert-danger";
                // }

                // var alertHTML = '<div class="alert alert-danger alert-dismissible fade show" data-timeout="3000" role="alert">'
                //                + "{{ message }}"
                //                + '<button type="button" class="btn btn-close" data-bs-dismiss="alert" aria-label="Close"></button>'
                //                + '</div>';
                // $("#message-container").html(alertHTML);
                // {% endfor %}
               
            }
        },
        error: function (xhr, textStatus, errorThrown) {
            // Handle error if the AJAX call fails
            console.log(errorThrown);
        }
        });
    }
    </script>
    
</body>

</html>
<br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br>

{% endblock content %}

Organizer/templates/Organizer/Status.html
{% extends 'Organizer/Head.html'%}
{% load static %}


{%  block content %}
<br><br><br><br>
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <table  align="center" cellpadding="10">
        <tr>
            {% for i in rdata %}
            <td>
                <div style="text-align:center;border:1px solid black;margin:22px;padding:20px">
                {{i.number}} 
                {% for j in data %}
                {% if i.number in j.rooms %}


                    <p>{{j.user}}</p>




                {% endif %}
                {% endfor %}
            </div>
            </td>
            {% if forloop.counter|divisibleby:4 %}
        </tr>
        <tr>
            {% endif %}
            {% endfor %}

    </table>
</body>
</html>
<br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br>
{% endblock content %}

Organizer/templates/Organizer/eventview.html
{% extends 'Organizer/Head.html'%}
{% load static %}
{% block content %}
<br><br><br><br>
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>

<body>
    <form action="" method="post">
        {% csrf_token %}
        <table border="1" align="center" cellpadding="10">
            <tr>
                <th>Event Code</th>
                <th>Rooms Alloted</th>
                <th>Action</th>
            </tr>
            <tr>
                <td>{{data.code}}</td>
                <td>{{data.rooms}}</td>
                <td>
                    {% if data.status == 1 %}
                    <a href="{% url 'org:status' data.id %}">Status</a> |
                    {% if data.is_private %}
                    <a href="{% url 'org:view_code' data.id %}">Viewcode</a> |
                    {% endif %}
                    <a href="{% url 'org:result' data.id %}">Result</a> |
                    <a href="{% url 'org:manuualy' data.id %}">Edit Result</a> |
                    <a href="{% url 'org:reopen' data.id %}">Re Open Event</a> |
                    <a href="{% url 'org:deleteevent' data.id %}">Delete Event</a>
                    {% else %}
                    <p>
                        <a href="{% url 'org:editevent' data.id %}">Edit EventCode</a> |
                        {% if data.is_private %}
                        <a href="{% url 'org:view_code' data.id %}">Viewcode</a> |
                        <a href="{% url 'org:add_capacity' data.id %}">Add Event Capacity</a> |
                        {% endif %}
                        <a href="{% url 'org:change_capacity' data.id %}">Change Group Capacity</a> |
                        <a href="{% url 'org:status' data.id %}">Status</a> |
                        <a href="{% url 'org:result' data.id %}">Result</a> |
                        <a href="{% url 'org:manuualy' data.id %}">Edit Result</a> |
                        <a href="{% url 'org:finishevent' data.id %}">Finish</a>
                      
                    </p>

                    {% endif %}
                </td>
            </tr>
        </table>
    </form>
    {% if mess == 1 %}
    <script>
        alert("This Event is finished you can view the results");
        window.location = "../../eventview/{{data.id}}";
    </script>

    {% endif %}
</body>

</html>
<br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br>
{% endblock content %}